name: Preview HTML in PR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    

permissions:
  actions: write
  contents: read
  issues: write

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build docs
        run: |
          mkdir -p dist
          cp index.html dist/index.html

      - name: Upload preview artifact
        id: docs_preview
        uses: pavi2410/html-preview-action@v5
        with:
          html_file: index.html
          site_root: dist
