name: Versioning

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Numéro de version (ex: 1.2.3)'
        required: true
        type: string

jobs:
  versioning:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Versioning Auto
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          VERSION="${{ github.event.inputs.version }}"
          PAYLOAD=$(jq -n --arg v "$VERSION" '{"version": $v}')
          curl -X POST "$WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD" \
            --fail-with-body || exit 1

